DISTRO = "lunnaos"
DISTRO_NAME = "LunnaOS"
DISTRO_VERSION = "Polaris"
DISTRO_CODENAME = "Sel(l)enne"

DISTRO_FEATURES:append = " systemd wayland opengl pam polkit bluetooth wifi"
DISTRO_FEATURES:remove = " x11"

INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"

KERNEL_LOCALVERSION = "-lunnaos"
TARGET_VENDOR = "-lunnaos"
