BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "lunnaos"
BBFILE_PATTERN_lunnaos = "^${LAYERDIR}/"
BBFILE_PRIORITY_lunnaos = "90"
LAYERSERIES_COMPAT_lunnaos = "scarthgap"
